id: ff09deec-49ab-4dee-8431-e9bf6e9a5d37
name: Product Gallery
type: composition
data: {}
order: 1600
path: /components/product-gallery
compositionId: 2c4530ee-29f6-4497-9a96-4b51f3786241
pathSegment: product-gallery
projectMapId: 40535f31-cdc1-4ac3-bb4d-2a008493b431
